export const ADD_COMMENT = 'ADD_COMMENT';
export const DISHES_LOADING = 'DISHES_LOADING'; // FETCH DISHES FROM SERVER
export const DISHES_FAILED = 'DISHES_FAILED' // FAILED TO FETCH DISHES FROM SERVER
export const ADD_DISHES = 'ADD_DISHES' //ADD DISHES TO STORE